language: R
sudo: false
cache:
  packages: true
warnings_are_errors: false
before_script:
  # ensure bioc-devel is being used
  - R -e 'BiocManager::install(version = "devel", ask=FALSE)'
  - R -e 'BiocManager::valid()'
r:
- bioc-devel
- bioc-release
r_packages:
# - covr
- tidyverse
- devtools
- roxygen2
- BiocManager
r_check_args:
 - "--no-vignettes --timings --no-multiarch"
bioc_required: true
bioc_check: true
bioc_packages:
- BiocCheck
- BiocFileCache
- GenomeInfoDbData
- GO.db
- org.Mm.eg.db
- org.Hs.eg.db
# after_success:
# - Rscript -e 'library(covr);codecov(quiet = FALSE)'
env: _R_CHECK_CRAN_INCOMING_=FALSE
os:
  - linux
  - osx
deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  file_glob: true
  file: "TimeSeriesExperiment*.tar.gz"
  on:
    tags: true
    repo: nlhuong/TimeSeriesExperiment
