# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-devel
sudo: false
warnings_are_errors: true

# BiocCheck
bioc_packages:
  - BiocCheck
  - BiocFileCache
  - GenomeInfoDbData
  - GO.db 
  - org.Mm.eg.db
  - org.Hs.eg.db

# customize build to add biocCheck

script:
  - R CMD build .
  - R CMD check --no-vignettes --timings --no-multiarch TimeSeriesExperiment_1.1.0.tar.gz 
  - echo "library(BiocCheck)" >> load_biocCheck.R
  - Rscript load_biocCheck.R
  - R CMD BiocCheck --new-package TimeSeriesExperiment_1.1.0.tar.gz

os:
  - linux

