# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-devel
sudo: false
warnings_are_errors: true

# BiocCheck
bioc_packages:
  - BiocCheck

# customize build to add biocCheck

script:
  - R CMD build . --no-resave-data --no-manual
  - R CMD check --no-build-vignettes vistimeseq_0.99.0.tar.gz
  - R CMD BiocCheck --new-package vistimeseq_0.99.0.tar.gz

os:
  - linux
  - osx

# after_success:
#  - R CMD BiocCheck --new-package --no-check-vignettes vistimeseq_0.99.0.tar.gz
