# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages
r: bioc-devel
sudo: false
warnings_are_errors: true

install:
  # Installs packages DESeq2 and phyloseq.
  - ./travis-tool.sh install_bioc DESeq2 phyloseq
  # Installs all packages in the DESCRIPTION file.
  - ./travis-tool.sh install_bioc_deps

# BiocCheck
bioc_packages:
  - BiocCheck

after_success:
  - R CMD BiocCheck --new-package --no-check-vignettes [package name]*.tar.gz
